### PR TITLE
feat: show all props gallery for button component

### LINKED ISSUE #469: Look into all-combinations story for complex components such as Button

### PR DESCRIPTION
**Pull request by shanberg**
Closes #469

- Add `withPropsCombinations` function to Button stories to demonstrate component props.

After:
image

### CODE REVIEW

**Comment by kaitmore** [comment]
I wonder if we can make this a bit more useful by showing the combination of props that will give you a result in this table. What if when you click on a button, it displays the props above the table?

**Comment by shanberg** [comment]
@kaitmore a simpler approach may be popping up an alert or something with those props, but anything more than what's currently present might require reimplementing the combination function at a slightly higher level, so I'm not sure how to approach that.

**Comment by kaitmore** [comment]
@shanberg I find alerts slightly annoying in this context but I think it's an ok intermediate solution. What about alert + copy to clipboard?

**Comment by shanberg** [comment]
@kaitmore There may be a conflict of interests here...

If this gallery is for demonstrating the possible types of buttons to validate button styles, we would want to click-to-copy to include all props, including `active` and other ephemeral things.

If instead it’s for selecting a button type to use in a UI, we would (probably?) want to limit click-to-copy to just `type`, `size`, `outline`, etc.

**Comment by kaitmore** [comment]
@shanberg I see what you mean. I think the latter makes the most sense. 

Another option is that we could simply give the table x and y values, although we would probably have to reorder it a bit for that to work.

**Comment by shanberg** [comment]
Maybe we can provide an alternate view with `showSource: true`?

image

**Comment by kaitmore** [comment]
@shanberg I've been playing around with a few options and just pushed up, let me know what you think.

**Comment by shanberg** [comment]
@kaitmore That's a big improvement. I'm happy with this.

**Pull request merged**
