### PR TITLE
feat: valid invalid input text

### PR DESCRIPTION
**Pull request by dgoldstein1**

### CODE REVIEW

**Comment by shanberg** [comment]
@dgoldstein1 

I think we need to do a better job of mapping out the states an input field can have, or leave that to the implementor. 

Right now a `required` field with content matching the field pattern will have have 'valid' style, regardless of whether `invalid` is true.

One solution would be to leave validation styles out of the default behavior entirely, and instead add a prop to modify the appearance alone, so that a developer can determine under what conditions a field should display a 'warning', 'danger', or 'success' color.

**Comment by kaitmore** [comment]
@dgoldstein1 What do you want to do with this PR?

**Comment by dgoldstein1** [comment]
@kaitmore thanks for resurfacing this.

I like stuart's idea of deferring button state to the implementer. I will make a PR to remove `invalid` / `valid` and have a `backgroundColor` prop, then the discussion can go from there.

**Comment by dgoldstein1** [comment]
Closing this in favor of having the implementer control colors through targeting the input field.

**Pull request closed without merging**
