### PR TITLE
feat: use Inter for base type

### PR DESCRIPTION
**Pull request by shanberg**
**Use Inter for default font.**

Currently we’re using the OS-preferred sans-serif. Using Inter instead provides us the knowledge that what we see on our screens as devs is going to be much closer to what users see on their screens, and improves visual consistency across installations on different machines, making it less likely that an odd OS font will cause odd UI layouts.

Inter is designed specifically for UIs, rather than a general-purpose type family like Helvetica Neue. It’s a great baseline for effective typography.

OS-preferred font are included as backup.

### CODE REVIEW

**Review by tilleryd — DISMISSED** [review]
@shanberg Doesn't `typeface-inter` need to imported into one of the JS modules to be leveraged?

**Comment by shanberg** [comment]
> @shanberg Doesn't `typeface-inter` need to imported into one of the JS modules to be leveraged?

@tilleryd No I thought you just had to look in the bathroom mirror and say "Inter...Inter...Inter" and it appears behind you

**Comment by shanberg** [comment]
@tilleryd I've got Inter working now in Storybook, but there remains the question of how to include it in apps using the component library. A simple approach would be to add the line it to the readme for library users, but I wonder if there's a more automatic solution.

**Comment by kaitmore** [comment]
@shanberg I think we can just add the "typeface-inter" import to our GlobalStyles.js:

```
import "typeface-inter";
```

**Review by kaitmore — APPROVED** [review]
LGTM

**Pull request merged**
