### PR TITLE
Move inter to peerDependencies

### PR DESCRIPTION
**Pull request by shanberg**

### CODE REVIEW

**Comment by kaitmore** [comment]
@tilleryd When you have a chance, can you test this on your machine by loading up this branch in the dashboard?

**Comment by tilleryd** [comment]
Hmm, can we still do this by importing just the `inter-ui` package in gm-ui-components but `inter-ui/inter.css` in the dashboard?

Error in CircleCI:
```
  ● Test suite failed to run

    Cannot find module 'inter-ui/inter.css' from 'index.js'

    > 1 | import "inter-ui/inter.css";
```

**Review by kaitmore — APPROVED** [review]
LGTM

**Review by tilleryd — APPROVED** [review]
LGTM

**Pull request merged**
