### PR TITLE
wip: feat: restyle error card

### PR DESCRIPTION
**Pull request by shanberg**
- Removes custom icon to reduce ambiguity
- Restyles error card for better fit in Grey Matter UIs

**After**
screen shot 2019-02-19 at 12 58 47 pm

### CODE REVIEW

**Comment by kaitmore** [comment]
Should this be themable?

**Comment by shanberg** [comment]
I wasn't able to update snapshots because of a local environment issue, so this PR needs that done before it’s ready.

Otherwise:
The error styles are now modeled after the Loading Spinner.
- Horizontal and vertical layouts
- Smaller overall size
- New 'message' and 'detail' props

**Comment by kaitmore** [comment]
@shanberg I tried this in the dashboard and it feels quite small and squished. I also think it's not really a "card" anymore - so if this is the final version, I propose we rename it.

image

**Comment by shanberg** [comment]
It does look like it’s being unnaturally squished. I avoided setting a width on it so I'm guessing the dashboard is trying to squish its contents. Investigating.

**Comment by shanberg** [comment]
I think it’s just being squished by the dashboard in your example.

After looking at the code and the use case for a bit, I think this should be an Error indicator, analogous to the Loading indicator `<Spinner>`.

If we find there's good enough reason to add styling beyond that, we should consider how to style it for that context. We could...
- Add additional states to the indicator beyond `vertical` and `horizontal`
- Add a `StateIndicatorCard` HOC analogous to Apple's iOS Hud-style components
- Add style overrides to the Dashboard element that renders this indicator
- Something else?

**Comment by kaitmore** [comment]
@shanberg It sounds like we're talking about 2 different components here. Could you explain the different use cases? If the dashboard case above isn't the primary use case, what is?

I like your idea of naming this `ErrorIndicator`. Then we can use this component to create a 'molecule' component `ErrorCard`.

**Comment by shanberg** [comment]
@kaitmore You said it in your second paragraph: there's a the essential `ErrorIndicator` _message_ and a `Card` _display method_.

The card bumps up the emphasis makes sense to deliver the message in an all-or-nothing interface context.

**Comment by kaitmore** [comment]
@shanberg Ok, that makes sense, just wanted to be sure I understood all the use cases this component is serving.

In that case, let's rename this component ErrorIndicator and make an issue to create an ErrorCard component?

**Comment by shanberg** [comment]
Canceled in lieu of #546.

**Pull request closed without merging**
